#**Prediction of IR and Raman bands with Group theory**
by Ignacio Migliaro, Olajumoke M. Ayeni

![picture](https://drive.google.com/uc?export=view&id=17fx7fkxRZgJq76w5pQSZfi6SEcZIXGX1)

<p align="justify">
Welcome to this notebook, where we'll be exploring the fascinating world of infrared (IR) and Raman spectroscopy! These analytical techniques allow us to probe the vibrations of molecules, giving us valuable information about their structure and properties. In this notebook, we'll be using the powerful framework of group theory to predict the IR and Raman bands of molecules. Group theory provides a systematic way of analyzing the symmetries and vibrations of molecules, helping us to understand the different types of vibrational modes and their corresponding spectral features. So, get ready to delve into the exciting world of molecular vibrations and spectroscopy, and let's use group theory to unlock the secrets of IR and Raman spectra!

## **Introduction:**

<p align="justify"> In chemistry, the study of molecular vibrations plays a critical role in understanding the chemical and physical properties of molecules. The vibrational spectroscopy techniques of IR (infrared) and Raman spectroscopy are used extensively to study the vibrational properties of molecules. Group theory and symmetry principles provide a powerful framework for understanding the vibrational modes of molecules and predicting their corresponding IR and Raman spectral bands. By applying group theory and symmetry, chemists can accurately assign and interpret the observed vibrational spectra of molecules. In this context, group theory and symmetry represent fundamental tools for analyzing and interpreting vibrational spectroscopy data, enabling a deeper understanding of the structural and electronic properties of molecules.

### VSEPR
<p align="justify"> Picture a group of friends planning to go out to dinner together. They want to sit at the same table but don't want to feel cramped or too far apart. Just like these friends, atoms in a molecule also want to stay as far apart as possible. VSEPR (Valence Shell Electron Pair Repulsion) theory helps us understand how atoms arrange themselves in a molecule by looking at the number of electron pairs in the valence (outermost) shell of the central atom. These electron pairs repel each other, leading to specific geometries that maximize the distance between them. For example, in a molecule with two electron pairs, the geometry is linear, just like two friends sitting across from each other at a table. In a molecule with three electron pairs, the geometry is trigonal planar, just like three friends sitting around a circular table. With VSEPR, we can predict the shape of a molecule, which is important because the shape determines the chemical and physical properties of the molecule. So, just like friends at a dinner table, atoms in a molecule also need their space!

![picture](https://drive.google.com/uc?export=view&id=1MSJRLd7qmoDme6Uh7Rex2u3NwpECuTln) ![picture](https://drive.google.com/uc?export=view&id=1dvbv02EynyDRvWlV9Dd7CB0m39P2uxUX) ![picture](https://drive.google.com/uc?export=view&id=1IYhNaIiIaCg5F5ypKLPPnBGm6i9uTLWv) ![picture](https://drive.google.com/uc?export=view&id=1WMs4DoGA15UrJurlX1gg5kyYmirtoRaG) ![picture](https://drive.google.com/uc?export=view&id=13FhfJCDu8q5j6xYBM4wBh2y7ijmhnHQT)

### Group Theory

<p align="justify"> Imagine you're playing a game of Tetris. The different pieces that fall down are like the atoms in a molecule, and the way they fit together to form a complete structure is like the symmetry and group properties of the molecule. Group theory is like the set of rules that dictate which pieces can fit together and how they can be arranged to form a complete structure. In chemistry, we use group theory to analyze the symmetry and properties of molecules, just like how we use the rules of Tetris to fit the different pieces together. By understanding the different symmetries and operations that a molecule can undergo, we can predict its properties, such as its dipole moment, electronic transitions, and spectroscopic behavior. Group theory provides a powerful framework for understanding the behavior of molecules, just like the rules of Tetris provide a framework for fitting the different pieces together to form a complete structure.

### Steps in how to determine IR bands and Raman bands using Group Theory
<p align="justify">
<ol>
<li>Figure out what shape the molecule has: To use group theory, we need to know what the molecule looks like. This means figuring out its shape and symmetry.</li>
<li>Predict the vibrations of the molecule: Molecules vibrate in different ways, and these vibrations can be analyzed using IR and Raman spectroscopy. We predict the different types of vibrations the molecule can have based on its shape and symmetry.</li>
<li>Decide which vibrations are IR active and which are Raman active: IR active vibrations involve a change in the dipole moment of the molecule, while Raman active vibrations involve a change in polarizability.</li>
<li>Interpret the results: Once we know which vibrations are IR and Raman active, we can analyze the resulting spectrum to learn more about the molecule's structure and properties.</li>
</ol>

### Selecting the VSEPR geometry of interest:

<p align="justify"> This is Step 1, here we will be selecting whichever molecule you wish to run the symmetry operations for in the dropdown menu and how to visualize the 3D model. The "X" represents the same atom that is attached to the atom center and the "E" represents a lone electron pair. For ease of comprehension the symmetry of the molecule is pre-defined, in most cases you will have to determine the point group of the molecule. The user is encouraged to test the code for all the different VSEPR geometries found here.  

![picture](https://drive.google.com/uc?export=view&id=14FVW3uDsWxXfDyL4qaRVezj_9mdLB3Or)

![picture](https://drive.google.com/uc?export=view&id=1XVuFt6si2TjU2ZXaejYNTAYIcW3DStBv)


## **Let the Journey Begin!**


In [1]:
#@title  **PREPARE THE NOTEBOOK: Run this cell to see instructions**
%%html
<marquee style='width: 50%; color: blue;'><b>Lets start here! Run the next code cell to download the dependencies for this notebook</b></marquee>

In [2]:
# @title *Download the dependencies for this notebook by running this cell:*
!git clone https://github.com/ignaciomigliaro/Group_theory_for_IR --quiet > /dev/null
!pip install py3Dmol -q
# @title Open .xyz file with cartesian coordinates
def open_file(file):
        path="./Group_theory_for_IR/Molecules/"+file+".xyz"
        with open(path) as ifile:
          file_name = "".join([x for x in ifile])
        return file_name

CO2=open_file("CO2")
BH3=open_file("BH3")
SO2=open_file("SO2")
CH4=open_file("CH4")
NH3=open_file("NH3")
H2O=open_file("H2O")
PF5=open_file("PF5")
SF4=open_file("SF4")
ClF3=open_file("ClF3")
PtCl4=open_file("PtCl4")
ClF5=open_file("ClF5")
FeCl6=open_file("FeCl6")
FeCl2=open_file("FeCl2")

## **STEP 1:**

In [3]:
# @title ***Here you will choose your molecule and determine its point group***
%%html
<marquee style='width: 50%; color: blue;'><b>Continue by running the next two code cells</b></marquee>

In [4]:
#@title *Choose geometry (AXE system) of the molecule from the drop down after running this cell*
from ipywidgets import interactive,fixed,IntSlider
import ipywidgets
import py3Dmol
import numpy as np

smis = [CO2,
        BH3,
        SO2,
        CH4,
        NH3,
        H2O,
        PF5,
        SF4,
        ClF3,
        FeCl6,
        ClF5,
        PtCl4,
        FeCl2]

def style_selector(idx, s):
    conf = smis[idx]
    return py3Dmol.view(data=conf, style=s).show()

a=interactive(style_selector,
         idx=ipywidgets.Dropdown(
             options=[('AX2', 0), ('AX3', 1), ('AX2E', 2) , ('AX4', 3), ('AX3E', 4), ('AX2E2', 5), ('AX5', 6), ('AX4E', 7), ('AX3E2', 8), ('AX6', 9), ('AX5E', 10), ('AX4E2', 11), ('AX2E4', 12)], #0-12 represents the molecules in their order in the list.
             value=12,
             description= 'Geometry:'),
         s=ipywidgets.Dropdown(
            options=['stick','line','sphere'],
            value='stick',
            description='Style:'))
display(a)

def point_group(x):
  if x == 0 :
    geometry="AX2"
    point_group="Di"
  if x == 1:
    geometry="AX3"
    point_group="D3h"
  if x == 2:
    geometry="AX2E"
    point_group="C2v"
  if x == 3:
    geometry="AX4"
    point_group="Td"
  if x == 4:
    geometry="AX3E"
    point_group="C3v"
  if x == 5:
    geometry='AX2E2'
    point_group='C2v'
  if x == 6:
    geometry='AX5'
    point_group='D3h'
  if x == 7:
    geometry='AX4E'
    point_group='C2v'
  if x == 8:
    geometry='AX3E2'
    point_group='C2v'
  if x == 9:
    geometry='AX6'
    point_group='Oh'
  if x == 10:
    geometry='AX5E'
    point_group='C4v'
  if x == 11:
    geometry='AX4E2'
    point_group='D4h'
  if x == 12:
    geometry='AX2E4'
    point_group='Di'
  return(geometry,point_group)

interactive(children=(Dropdown(description='Geometry:', index=12, options=(('AX2', 0), ('AX3', 1), ('AX2E', 2)…

In [9]:
#@title *Deduce the point group of the molecule by running this code cell*
import numpy as np
def file_matrix(file):
    split=file.split()
    mat=np.array(split[2:])
    row=int(len(mat)/4)
    matrix=mat.reshape(row,4)
    return(matrix)
#obtains slider value to pass and find xyz matrix.
x=int(a.kwargs['idx'])
molecule,pg=point_group(x)
print("Your molecular geometry is:",molecule)
print("Your point group is:",pg)
file=smis[x]
name_atoms=file_matrix(file)
atoms=np.array(name_atoms[:,1:])
atoms=atoms.astype(float)
natoms=int(np.shape(atoms)[0])

Your molecular geometry is: AX4
Your point group is: Td


## **STEP 2:**

In [10]:
# @title ***Next, you will apply symmetry operations on your molecule and determine the number of unchanged positions***
%%html
<marquee style='width: 50%; color: blue;'><b>Dont rush! take time to read the text and then run the next two code cells only one time each</b></marquee>

### **Lets talk about Symmetry operations!**
<p align="justify">
Symmetry operations are a way of describing the different ways in which a molecule can be transformed while maintaining its overall shape and structure. One way to represent symmetry operations is through matrices.
Matrices are mathematical objects that can be used to transform vectors (i.e. quantities that have both magnitude and direction) and points in space. In the context of symmetry operations, we use matrices to represent the way in which the molecule is transformed by the operation.
For example, consider a molecule that has a plane of symmetry. To represent this symmetry operation as a matrix, we can use a 3x3 matrix that describes the transformation of each coordinate in space. The elements of the matrix correspond to the x, y, and z components of the transformed vector.
When the matrix is applied to the original molecule, the resulting molecule is reflected across the plane of symmetry, while maintaining its overall shape and structure.
Similarly, other symmetry operations such as rotations and inversions can also be represented as matrices. By using matrices to represent symmetry operations, we can use mathematical tools to analyze the symmetry properties of a molecule and predict its behavior in various situations, such as in IR and Raman spectroscopy.

 ***Symmetry operations can be written as numpy arrays.***

<p align="justify"> Symmetry operations can also be represented using numpy arrays, which are a type of data structure in Python that allows for efficient manipulation of large arrays and matrices.

In the context of symmetry operations, numpy arrays can be used to represent the transformation of a molecule's coordinates under a particular symmetry operation. For example, if a molecule has a C2 axis of rotation, we can represent this operation using a 3x3 numpy array that describes the transformation of each coordinate in space.

$C_2$
 \begin{pmatrix}
cos(\theta) & -sin(\theta) & 0\\
sin(\theta) & cos(\theta) & 0\\
0 & 0 & 1
\end{pmatrix}
Here $\theta = \pi$, therefore $cos(\pi)=1$ and $sin(\pi)=0$, this is the definition for a rotation on the z-axis.

<img src="https://drive.google.com/uc?export=view&id=1ZeDMfi3x5ONpun4tQN3F5tINNMyEiWnQ" width=200>


<p align="justify"> To apply this symmetry operation to a molecule, we can simply multiply the coordinates of each atom in the molecule by the numpy array. This results in a transformed molecule that has the same overall shape and structure, but with different coordinates for each atom.

Using numpy arrays to represent symmetry operations can be very useful for computational chemistry and spectroscopy, as it allows for fast and efficient calculations of the effects of different symmetry operations on a molecule.

In [11]:
#@title *Now run symmetry operations as arrays*


import sympy as sp
import math
from numpy.linalg import multi_dot
###These are the some symmetry operations
def identity_matrix(natoms):
  E=np.identity(3)
  E_matrix=np.dot(atoms,E)
  return(E,E_matrix)

def c4_matrix(): #This is a 90 degree proper rotation on Z-axis
  C4=np.array([[round(sp.cos(sp.pi/2),4),(round(-sp.sin(sp.pi/2), 4)),0],[round(sp.sin(sp.pi/2), 4),(round(sp.cos(sp.pi/2), 4)),0],[0,0,1]])
  c4_matrix=np.dot(atoms,C4)
  return(C4,c4_matrix)

def c4y_matrix(): #This is a 90 degree proper rotation on y-axis
  C4y=np.array([[round(sp.cos(sp.pi/2),4),0,(round(-sp.sin(sp.pi/2), 4))],[0,1,0],[round(sp.sin(sp.pi/2), 4),0,(round(sp.cos(sp.pi/2), 4))]])
  c4y_matrix=np.dot(atoms,C4y)
  return(C4y,c4y_matrix)

def c2_matrix_z(): #This is a 180 degree proper rotation on Z-axis
  C2=np.array([[sp.cos(sp.pi),-sp.sin(sp.pi),0],[sp.sin(sp.pi),sp.cos(sp.pi),0],[0,0,1]])
  c2_matrix=np.dot(atoms,C2)
  return(C2,c2_matrix)

def c2_x(): #This is a 180 degree proper rotation on x-axis
  C21=np.array([[1,0,0],[0,sp.cos(sp.pi),-sp.sin(sp.pi)],[0,sp.sin(sp.pi),sp.cos(sp.pi)]])
  c2_prime_matrix=np.dot(atoms,C21)
  return(C21,c2_prime_matrix)

def c2_y(): #This is a 180 degree proper rotation on y-axis
  C21y=np.array([[sp.cos(sp.pi),0,-sp.sin(sp.pi)],[0,1,0],[sp.sin(sp.pi),0,sp.cos(sp.pi)]])
  c2y_prime_matrix=np.dot(atoms,C21y)
  return(C21y,c2y_prime_matrix)

def c2_dprime(): #This is a 180 degree proper rotation in between the axis
  c2_dprime=np.array([[0,-1,0],[-1,0,0],[0,0,-1]])
  c2_dprime_matrix=np.dot(atoms,c2_dprime)
  return(c2_dprime,c2_dprime_matrix)
  #c2 on z-axis

def c3_matrix_z(): # This is a C3 (120 degree) rotation on the Z-axis
  C3=np.array([[round(sp.cos(sp.pi/1.5), 8),(round(-sp.sin(sp.pi/1.5), 8)),0],[round(sp.sin(sp.pi/1.5),8),(round(sp.cos(sp.pi/1.5), 8)) ,0],[0,0,1]])
  c3_matrix=np.dot(atoms,C3)
  return(C3,c3_matrix)
"""def c3_matrix_z(): # The result is thesame as the above commented lines of code
  theta = 2 * math.pi / 3
  c3 = np.array([[-math.cos(theta), -math.sin(theta), 0],
                           [math.sin(theta), -math.cos(theta), 0],
                           [0, 0, 1]])
  c3_matrix=np.dot(atoms,c3)
  return(c3,c3_matrix)"""


def c_3_matrix_x(): # This is a C3 (120 degree) rotation on x-axis
  C_3=np.array([[1,0,0],[0,round(sp.cos(sp.pi/1.5), 4),(round(-sp.sin(sp.pi/1.5), 4))],[0,round(sp.sin(sp.pi/1.5),4),(round(sp.cos(sp.pi/1.5),4))]])
  c_3_matrix=np.dot(atoms,C_3)
  return(C_3,c_3_matrix)

def c_3_matrix_y(): # This is a C3 (120 degree) rotation on y-axis
  C_32=np.array([[round(sp.cos(sp.pi/1.5), 4),0,(round(-sp.sin(sp.pi/1.5), 4))],[0,1,0],[round(sp.sin(sp.pi/1.5),4),0,(round(sp.cos(sp.pi/1.5),4))]])
  c_32_matrix=np.dot(atoms,C_32)
  return(C_32,c_32_matrix)

def c3_dprime(): # This is a C3 (120 degree) rotation between the axis
  C32=np.array([[0,1,0],[0,0,1],[1,0,0]])
  c3_dprime=np.dot(atoms,C32)
  return(C32,c3_dprime)

def inversion(natoms):
   E=np.identity(3)
   I_matrix=np.dot(atoms,-E)
   return(-E,I_matrix)

def s2(): # This is a 180 degree improper rotation along the Z-axis
  C2=np.array([[sp.cos(sp.pi),-sp.sin(sp.pi),0],[sp.sin(sp.pi),sp.cos(sp.pi),0],[0,0,1]])
  sh=np.array([[1,0,0],[0,1,0],[0,0,-1]])
  s2=np.dot(C2,sh)
  s2_matrix=multi_dot([atoms,C2,sh])
  return(s2,s2_matrix)

def s3(): # This is a 120 degree improper rotation along the Z-axis
  C3=np.array([[round(sp.cos(sp.pi/1.5), 4),(round(-sp.sin(sp.pi/1.5), 4)),0],[round(sp.sin(sp.pi/1.5),4) ,(round(sp.cos(sp.pi/1.5), 4)) ,0],[0,0,1]])
  sh=np.array([[1,0,0],[0,1,0],[0,0,-1]])
  s3=np.dot(C3,sh)
  s3_matrix=multi_dot([atoms,C3,sh])
  return(s3,s3_matrix)

def s_4():  #This is a 90 degree improper rotation in between the axis
  C_4=np.array([[round(sp.cos(sp.pi/2),4),(round(-sp.sin(sp.pi/2), 4)),0],[round(-sp.sin(sp.pi/2), 4),(round(sp.cos(sp.pi/2), 4)),0],[0,0,-1]])
  sh=np.array([[1,0,0],[0,-1,0],[0,0,1]])
  s_4=np.dot(C_4,sh)
  s_4_matrix=multi_dot([atoms,C_4,sh])
  return(s_4,s_4_matrix)

def c_4_matrix():  # 90 degree proper rotation in between the axis
  C_4=np.array([[round(sp.cos(sp.pi/2),4),(round(-sp.sin(sp.pi/2), 4)),0],[round(-sp.sin(sp.pi/2), 4),(round(sp.cos(sp.pi/2), 4)),0],[0,0,-1]])
  c_4_matrix=np.dot(atoms,C_4)
  return(C_4,c_4_matrix)

def s4(): # This is the 90 degree improper rotation on the Z-axis.
  C4=np.array([[round(sp.cos(sp.pi/2),4),(round(-sp.sin(sp.pi/2), 4)),0],[round(sp.sin(sp.pi/2), 4),(round(sp.cos(sp.pi/2), 4)),0],[0,0,1]])
  sh=np.array([[1,0,0],[0,1,0],[0,0,-1]])
  s4=np.dot(C4,sh)
  s4_matrix=multi_dot([atoms,C4,sh])
  return(s4,s4_matrix)

def s6(): # This is the 60 degree improper rotation on the Z-axis.
  C6=np.array([[round(sp.cos(sp.pi/3),4),(round(-sp.sin(sp.pi/3), 4)),0],[round(sp.sin(sp.pi/3), 4),(round(sp.cos(sp.pi/3), 4)),0],[0,0,1]])
  sh=np.array([[1,0,0],[0,1,0],[0,0,-1]])
  s6=np.dot(C6,sh)
  s6_matrix=multi_dot([atoms,C6,sh])
  return(s6,s6_matrix)

def s62(): # This is the 60 degree improper rotation in between the axis.
  s62=np.array([[0,1,0],[0,0,1],[-1,0,0]])
  s62_matrix=np.dot(atoms,s62)
  return(s62,s62_matrix)

def sigmah(): #This is the horizontal reflection
  sh=np.array([[1,0,0],[0,1,0],[0,0,-1]])
  sigmah=np.dot(atoms,sh)
  return(sh,sigmah)

def sigmav(): # This is the vertical reflection plane along the y-axis and also contains the principal axis
  sv=np.array([[-1,0,0],[0,1,0],[0,0,1]])
  sigmav=np.dot(atoms,sv)
  return(sv,sigmav)

def sigmav_xz(): # This is the vertical reflection plane along the X- axis and also contains the principal axis
  Sv=np.array([[1,0,0],[0,-1,0],[0,0,1]])
  sigmav_xz=np.dot(atoms,Sv)
  return(Sv,sigmav_xz)

def sigmav_xy():
  Sv=np.array([[1,0,0],[0,1,0],[0,0,-1]])
  sigmav_xy=np.dot(atoms,Sv)
  return(Sv,sigmav_xy)

def sigmad(): # This is the diagonal/dihedral reflection plane (A vertical mirror plane that bisects the angle between two C2 axes)
  sd=np.array([[-1,0,0],[0,-1,0],[0,0,1]])
  sigmad=np.dot(atoms,sd)
  return(sd,sigmad)

def sigmad1(): # This is the diagonal/dihedral reflection plane between the axis (reflection along the diagonal of a 3D space, which goes through the origin which goes through the origin and two axes)
  sd1=np.array([[1, 0, 0], [0, -1, 0], [0, 0, 1]])
  sigmad1=np.dot(atoms,sd1)
  return(sd1,sigmad1)

E=identity_matrix(natoms)
C4=c4_matrix()
c22=c2_dprime()
I=inversion(natoms)
S4=s4()
S6=s6()
S62=s62()
SH=sigmah()
SV=sigmav()
SD=sigmad()

#Determines how many unmoved atoms are left in each symmetry operation
def um(symmetry):
  rho=0
  row0=0
  for row1 in symmetry:
    if np.array_equal(row1,atoms[row0]):
      rho += 1
    row0 += 1
  return rho

In [12]:
#@title *Apply the symmetry operations on your chosen molecule and find out the number of unmoved positions*
#code to assign symmetry operations to each point group and then return the resulting matrix.
#def symmetry_designation:
atoms2=atoms
atoms = np.delete(atoms, (0), axis=0)
if pg == "Di":
    print("Your point group is:",pg)
    print("Symmetry operations used in your point group are:")
    print("E,C∞,C2\',i,S∞,σ∞")
    E,E_1=identity_matrix(natoms)
    C2,C2_1=c2_matrix_z()
    C21,C21_1=c2_x()
    c22,c22_1=c2_dprime()
    I,I_1= inversion(natoms)
    Sv,Sv_1=sigmav()
    Sv1,Sv1_1=sigmav_xz()
    Sv2,Sv2_1=sigmav_xy()
    G=np.array([um(E_1),um(C2_1),um(C21_1),um(c22_1),um(I_1),um(Sv2_1),um(Sv1_1),um(Sv_1)])

    print("Initial atom coordinates matrix:\n",atoms)
    print("Identity matrix:\n",E)
    print("Resulting matrix after E:\n",E_1)
    print("C∞ matrix: \n",C2)
    print("Resulting matrix after C∞:\n",C2_1)
    print("Inversion matrix:\n",I)
    print("Resulting matrix after I: \n",I_1 )
    print("σ∞ matrix: \n",Sv)
    print("Resulting matrix after σ∞ matrix: \n",Sv_1 )
    print("σ∞ matrix: \n",Sv1)
    print("Resulting matrix after σ∞ matrix: \n",Sv1_1 )
    print("σ∞ matrix: \n",Sv2)
    print("Resulting matrix after σ∞ matrix: \n",Sv2_1 )

elif pg == "D3h":
    print("Your point group is:",pg)
    print("Symmetry operations used in your point group are:")
    print("E, C3, C2, σh, S3, σv")
    E,E_1=identity_matrix(natoms)
    C3,C3_1=c3_matrix_z()
    C21,C21_1=c2_y()
    sh,sh_1=sigmah()
    S3,S3_1=s3()
    Sv,Sv_1=sigmav()
    G=np.array([um(E_1),um(C3_1),um(C21_1),um(sh_1),um(S3_1),um(Sv_1)])

    print("Initial atom coordinates matrix:\n",atoms)
    print("Identity matrix:\n",E)
    print("Resulting matrix after E: \n",E_1 )
    print("C3 matrix: \n",C3)
    print("Resulting matrix after C3: \n",C3_1)
    print("C2 matrix: \n",C21)
    print("Resulting matrix after C2: \n",C21_1)
    print("σh matrix: \n",sh)
    print("Resulting matrix after σh matrix: \n",sh_1 )
    print("S3 matrix: \n",S3)
    print("Resulting matrix after S3:\n",S3_1)
    print("σv matrix: \n",Sv)
    print("Resulting matrix after σv_xz matrix: \n",Sv_1 )

elif pg =="Oh":
    print("Your point group is:",pg)
    print("Symmetry operations used in your point group are:")
    print("E, C3'',C2'', C4, C2', i, S4, S6, σh, σd")
    E,E_1=identity_matrix(natoms)
    C4,C4_1=c4_matrix()
    C32,C32_1=c3_dprime()
    C2,C2_1=c2_matrix_z()
    C21,C21_1=c2_x()
    c22,c22_1=c2_dprime()
    I,I_1= inversion(natoms)
    S4,S4_1=s4()
    S62,S62_1=s62()
    sh,sh_1=sigmah()
    sv,sv_1=sigmav()
    sd,sd_1=sigmad()
    G=np.array([um(E_1),um(C32_1),um(c22_1),um(C4_1),um(C21_1),um(I_1),um(S4_1),um(S62_1),um(sh_1),um(sd_1)])

    print("Initial atom coordinates matrix:\n",atoms)
    print("Identity matrix:\n",E)
    print("Resulting matrix after E: \n",E_1 )
    print("C3'' matrix: \n",C32)
    print("Resulting matrix after C3'': \n",C32_1)
    print("C2'' matrix: \n",c22)
    print("Resulting matrix after C2: \n",c22_1)
    print("C4 matrix: \n",C4)
    print("Resulting matrix after C4: \n",C4_1)
    print("C2' matrix: \n",C21)
    print("Resulting matrix after C2: \n",C21_1)
    print("Inversion matrix:\n",I)
    print("Resulting matrix after I: \n",I_1 )
    print("S4 matrix: \n",S4)
    print("Resulting matrix after S4:\n",S4_1)
    print("S6'' matrix: \n",S62)
    print("Resulting matrix after S6'':\n",S62_1)
    print("σh matrix: \n",sh)
    print("Resulting matrix after σh matrix: \n",sh_1 )
    print("σd matrix: \n",sd)
    print("Resulting matrix after σd matrix: \n",sd_1 )


elif pg == "C2v":
    print("Your point group is:",pg)
    print("Symmetry operations used in your point group are:")
    print("E, C2, σv(xz),σv(yz)")
    E,E_1=identity_matrix(natoms)
    C2,C2_1=c2_matrix_z()
    sv,sv_1=sigmav()
    Sv,Sv_1=sigmav_xz()
    G=np.array([um(E_1),um(C2_1),um(Sv_1),um(sv_1)])

    print("Initial atom coordinates matrix:\n",atoms)
    print("Identity matrix:\n",E)
    print("Resulting matrix after E:\n",E_1)
    print("C2 matrix: \n",C2)
    print("Resulting matrix after C2: \n",C2_1)
    print("σv matrix: \n",sv)
    print("Resulting matrix after σv matrix: \n",sv_1 )
    print("σv_xz matrix: \n",Sv)
    print("Resulting matrix after σv_xz matrix: \n",Sv_1 )

elif pg == "Td":
    print("Your point group is:",pg)
    print("Symmetry operations used in your point group are:")
    print("E, C3, C2, S4, σd")
    E,E_1=identity_matrix(natoms)
    C3,C3_1=c3_matrix_z()
    C2,C2_1=c2_x()
    S4,S4_1=s_4()
    sd1,sd1_1=sigmad1()
    G=np.array([um(E_1),um(C3_1),um(C2_1),um(S4_1),um(sd1_1)])

    print("Initial atom coordinates matrix:\n",atoms)
    print("Identity matrix:\n",E)
    print("Resulting matrix after E:\n",E_1)
    print("C3 matrix: \n",C3)
    print("Resulting matrix after C3:\n",C3_1)
    print("C2 matrix: \n",C2)
    print("Resulting matrix after C2:\n",C2_1)
    print("S4 matrix: \n",S4)
    print("Resulting matrix after S4:\n",S4_1)
    print("σd matrix: \n",sd1)
    print("Resulting matrix after σd matrix: \n",sd1_1 )

elif pg == "C3v":
    print("Your point group is:",pg)
    print("Symmetry operations used in your point group are:")
    print("E, C3, σv")
    E,E_1=identity_matrix(natoms)
    C3,C3_1=c3_matrix_z()
    Sv,Sv_1=sigmav_xz()
    G=np.array([um(E_1),um(C3_1),um(Sv_1)])

    print("Initial atom coordinates matrix:\n",atoms)
    print("Identity matrix:\n",E)
    print("Resulting matrix after E:\n",E_1)
    print("C3 matrix: \n",C3)
    print("Resulting matrix after C3:\n",C3_1)
    print("σv_xz matrix: \n",Sv)
    print("Resulting matrix after σv matrix: \n",Sv_1 )

elif pg == "C4v":
    print("Your point group is:",pg)
    print("Symmetry operations used in your point group are:")
    print("E, C4, C2, σv, σd")
    E,E_1=identity_matrix(natoms)
    C4,C4_1=c4_matrix()
    C2,C2_1=c2_matrix_z()
    sv,sv_1=sigmav()
    sd,sd_1=sigmad()
    G=np.array([um(E_1),um(C4_1),um(C2_1),um(sv_1),um(sd_1)])

    print("Initial atom coordinates matrix:\n",atoms)
    print("Identity matrix:\n",E)
    print("Resulting matrix after E:\n",E_1)
    print("C4 matrix: \n",C4)
    print("Resulting matrix after C4: \n",C4_1)
    print("C2 matrix: \n",C2)
    print("Resulting matrix after C2:\n",C2_1)
    print("σv matrix: \n",sv)
    print("Resulting matrix after σv matrix: \n",sv_1 )
    print("σd matrix: \n",sd)
    print("Resulting matrix after σd matrix: \n",sd_1 )

elif pg == "D4h":
    print("Your point group is:",pg)
    print("Symmetry operations used in your point group are:")
    print("E, C4, C2, C2', C2'', i, S4, σh, σd, σv")
    E,E_1=identity_matrix(natoms)
    C4,C4_1=c4_matrix()
    C2,C2_1=c2_matrix_z()
    C21,C21_1=c2_x()
    c22,c22_1=c2_dprime()
    I,I_1= inversion(natoms)
    S4,S4_1=s4()
    sh,sh_1=sigmah()
    sv,sv_1=sigmav()
    sd,sd_1=sigmad()
    G=np.array([um(E_1),um(C4_1),um(C2_1),um(C21_1),um(c22_1),um(I_1),um(S4_1),um(sh_1),um(sv_1),um(sd_1)])

    print("Initial atom coordinates matrix:\n",atoms)
    print("Identity matrix:\n",E)
    print("Resulting matrix after E: \n",E_1 )
    print("C4 matrix: \n",C4)
    print("Resulting matrix after C4: \n",C4_1)
    print("C2 matrix: \n",C2)
    print("Resulting matrix after C2: \n",C2_1)
    print("C2' matrix: \n",C21)
    print("Resulting matrix after C2: \n",C21_1)
    print("C2'' matrix: \n",c22)
    print("Resulting matrix after C2: \n",c22_1)
    print("Inversion matrix:\n",I)
    print("Resulting matrix after I: \n",I_1 )
    print("S4 matrix: \n",S4)
    print("Resulting matrix after S4:\n",S4_1)
    print("σv matrix: \n",sv)
    print("Resulting matrix after σv matrix: \n",sv_1 )
    print("σh matrix: \n",sh)
    print("Resulting matrix after σh matrix: \n",sh_1 )
    print("σd matrix: \n",sd)
    print("Resulting matrix after σd matrix: \n",sd_1 )


else:
  print("Not available")


print("Number of unmoved positions",G) #This returns the number of unmoved atoms around a central atom after the operation in the order of symmetry operation in the point group as listed in the result above.

Your point group is: Td
Symmetry operations used in your point group are:
E, C3, C2, S4, σd
Initial atom coordinates matrix:
 [[ 0.          0.          0.        ]
 [ 0.963       0.         -0.325     ]
 [-0.44562905 -0.77479194 -0.34731281]
 [ 0.          0.          1.09      ]
 [-0.44562905  0.77479194 -0.34731281]]
Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Resulting matrix after E:
 [[ 0.          0.          0.        ]
 [ 0.963       0.         -0.325     ]
 [-0.44562905 -0.77479194 -0.34731281]
 [ 0.          0.          1.09      ]
 [-0.44562905  0.77479194 -0.34731281]]
C3 matrix: 
 [[-0.50000000 -0.86602540 0]
 [0.86602540 -0.50000000 0]
 [0 0 1]]
Resulting matrix after C3:
 [[0 0 0.0]
 [-0.481500000000000 -0.833982460535131 -0.325]
 [-0.448174976489011 0.773322051897054 -0.347312812]
 [0 0 1.09]
 [0.893804030489011 -0.00146989210294601 -0.347312812]]
C2 matrix: 
 [[1 0 0]
 [0 -1 0]
 [0 0 -1]]
Resulting matrix after C2:
 [[0.0 0 0]
 [0.963 0 0.325000000000000]
 

## **STEP 3:**

In [13]:
# @title ***Next, you will predict the vibrations of the molecule:***
%%html
<marquee style='width: 50%; color: blue;'><b>Dont rush! take time to read the text and then run the next five code cells only one time each</b></marquee>

### *What does stretching vibrations of molecules look like?*

<p align="justify"> Think of stretching vibrations as molecular yoga poses! Similar to how various yoga postures stretch and flex various body regions, various stretching vibrations in molecules stretch and flex various chemical bonds. IR and Raman vibrational frequencies are important for characterizing functional groups and chemical properties. Scientists can use IR and Raman spectra to learn more about molecular yoga poses and properties, and possibly find a new way to stretch molecules.

<p align="justify">In this section, we will calculate the irreducible representations to determine the IR/Raman vibrations of the molecules. However, this notebook is currently designed to deduce the strecthing vibrations of atoms surrounding a central atom(SELECTED stretching vibrations).

<center>

![picture](https://drive.google.com/uc?export=view&id=1UTLEuBFjLdqhrzQHdVwU05AsFin-I031)


<p align="justify">The irreducible representations of each point group and their accompanying matrix characters are contained in a character table, a two-dimensional chart connected with a point group. Also, it includes the Mulliken symbols used to describe the size of irreducible representations.

<p align="justify">The character table can be read from an Excel file into a special type of table called a DataFrame using a Pandas library to perform some calculations with the "order of the group,” “the number of unmoved positions after each operation,” and “characters.”


<p align="justify">The number of irreducible representations usually is done by taking the sum of products of the number of unmoved atoms, the coeeficient of each symmetry operation and the character of the irreducible representation then didviding the sum by the order of the group.

<p align="justify">This calculations can be done all at once in the dataframe and returned as a column(M).

When M=0, that particular irreducible representation is absent.

<p align="justify">When M=1,2....; there are that number of the irreducible representation present and is written as the coefficient of the irreducible representations that makes up that selected vibration.

***For example; from the display below:***

![picture](https://drive.google.com/uc?export=view&id=1LnQB9wvE2k7GNQILBm2ycdzme8ZwhVab)

***The ireducible representations = 1.0 A1 + 1.0 B2 = A1 + B2***



<p align="justify">Vibrations that are IR active corresponds to "X", "Y", or "Z" in the linear function column while those that are Raman active corresponds any term in the quadratic function column. M gives the number of IR or Raman Bands present.


In [14]:
#@title *Call out Character table as dataframe.*
import pandas as pd
df=pd.read_excel('./Group_theory_for_IR/charactertables.xlsx',pg)
searchfor=['x','y','z']
df2=df[~df['Linear'].isnull()]
rows=len(df2.index)

D=df.iloc[-1:,1:].dropna(axis='columns').to_numpy()
D.flatten()
h=np.sum(D) # This gives the order of the group
df

Td  E  C3  C2  S4  sd    Linear  Rotational               Quadratic
0  A1  1   1   1   1   1       NaN         NaN            x2 + y2 + z2
1  A2  1   1   1  -1  -1       NaN         NaN                     NaN
2   E  2  -1   2   0   0       NaN         NaN  2z2 - x2 - y2, x2 - y2
3  T1  3   0  -1   1  -1       NaN  Rx, Ry, Rz                     NaN
4  T2  3   0  -1  -1   1  x, y, z          NaN              xz, yz, xy
5   #  1   8   3   6   6       NaN         NaN                     NaN

In [15]:
#@title *Deduce the order of the group, number of unmoved atoms, and symmetry operations.*

#Calculating the numbers of Irreducible representations.
M=[]
rows=len(df.index)-1
for i in range(rows):
  N1=0
  row_list=df.loc[i].to_list()
  row_list=row_list[1:-3]
  [float(i) for i in row_list]
  for j in range(len(row_list)):
    N=(G[j]*D[0,j]*row_list[j])
    N1 =N1+ N
  N2=N1/h
  M.append(N2)
M.append(0)
df['M']=M #the coefficient of the particular irreducible representation present
df


#Order of the group, Number of unmoved atoms, and Symmetry operations.
print("The number of unmoved atoms=",(G))
print("The coefficient of each symmetry operation=",(D))
print("The order of the group=", (h))

The number of unmoved atoms= [5 2 1 1 3]
The coefficient of each symmetry operation= [[1 8 3 6 6]]
The order of the group= 24


In [16]:
#@title *Deduce the irreducible representations for your molecule:*
df[df.M > 0]

Td  E  C3  C2  S4  sd    Linear Rotational     Quadratic    M
0  A1  1   1   1   1   1       NaN        NaN  x2 + y2 + z2  2.0
4  T2  3   0  -1  -1   1  x, y, z         NaN    xz, yz, xy  1.0

In [17]:
#@title *Deduce which representations correspond to an IR active Bands.*
df[df.Linear.notna() & df.M > 0]

Td  E  C3  C2  S4  sd    Linear Rotational   Quadratic    M
4  T2  3   0  -1  -1   1  x, y, z         NaN  xz, yz, xy  1.0

In [18]:
#@title *Deduce which representations correspond to an Raman active Bands.*
df[df.Quadratic.notna() & df.M > 0]

Td  E  C3  C2  S4  sd    Linear Rotational     Quadratic    M
0  A1  1   1   1   1   1       NaN        NaN  x2 + y2 + z2  2.0
4  T2  3   0  -1  -1   1  x, y, z         NaN    xz, yz, xy  1.0

## **Conclusion**

<p align="justify">
In this notebook, we were able to go from an xyz coordinate of a specific VSEPR geometry to predicting the IR bands. Ultimately, the goal of this notebook is to help you develop an intuition for the relationship between molecular geometry and IR spectra. By practicing with different molecules and geometries, you'll gain a deeper understanding of how to interpret IR spectra and how to use them to identify unknown compounds. So keep practicing and have fun exploring the fascinating world of molecular vibrations!

## **References**

1. Chemical applications of group theory (Cotton, F. Albert). Harry B. Gray
Journal of Chemical Education 1964 41 (2), 113
DOI: 10.1021/ed041p113.2
2. https://symotter.org/